// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2GBiAVNX3kNr14Vl5k6-oBdYZr_zMeR8',
    appId: '1:459614394196:web:3024c80dbaae6fb32a9ac1',
    messagingSenderId: '459614394196',
    projectId: 'flutter-chat-app-3fdc4',
    authDomain: 'flutter-chat-app-3fdc4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3fdc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroaKgKkKS_WpM4zPhWOSacJGSoIIXrM0',
    appId: '1:459614394196:android:238cc46118efa02c2a9ac1',
    messagingSenderId: '459614394196',
    projectId: 'flutter-chat-app-3fdc4',
    storageBucket: 'flutter-chat-app-3fdc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc8ecvKoZYSQvAd_WCZrVKq9aOAvUgsOw',
    appId: '1:459614394196:ios:72c299ad8efb86ef2a9ac1',
    messagingSenderId: '459614394196',
    projectId: 'flutter-chat-app-3fdc4',
    storageBucket: 'flutter-chat-app-3fdc4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc8ecvKoZYSQvAd_WCZrVKq9aOAvUgsOw',
    appId: '1:459614394196:ios:72c299ad8efb86ef2a9ac1',
    messagingSenderId: '459614394196',
    projectId: 'flutter-chat-app-3fdc4',
    storageBucket: 'flutter-chat-app-3fdc4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2GBiAVNX3kNr14Vl5k6-oBdYZr_zMeR8',
    appId: '1:459614394196:web:7ca7a49cfc1fb2c22a9ac1',
    messagingSenderId: '459614394196',
    projectId: 'flutter-chat-app-3fdc4',
    authDomain: 'flutter-chat-app-3fdc4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3fdc4.firebasestorage.app',
  );

}